name: kanban_taskmanager
description: "KanBan Task manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8
#  flutter_screenutil: ^5.9.3
#  easy_localization: ^3.0.7
#  flutter_bloc: ^8.1.5
  #  get_it: ^7.7.0
  #  alice: ^0.3.2
  get_it: ^7.7.0
  azl_domain:
    path: domain
  azl_data:
    path: data
  azl_presentation:
    path: presentation
  environments:
    path: environments

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.1
  test: ^1.25.2


flutter:
  uses-material-design: true
  assets:
    #    - assets/icons/
    #    - assets/fonts/
    #    - assets/images/
    - assets/locales/