name: azl_domain
description: Clean Domain Layer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  azl_data:
    path: ../data

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  test: ^1.25.2